### ISSUE TITLE
Add daily notifications for saved search criteria

### ISSUE THREAD

**Issue by rockg** [mayanez/flight_scraper#3]
My main reason for implementing the calendar search is that I'm looking for a flight with very flexible dates and want to have a daily notification of prices of all flights.  I looked around and do not see any functionality like this.  I think this will require a few things:
1. Saved search criteria that will every day execute the search and send out the notification.
2. Saved email account information in order to send out the email.
3. A way to modify search criteria--turn the searches on or off once the flight no longer needs to be searched.
4. Command-line ability (already on your list) as the main interaction for this would not be through the webpage.
5. How to automate daily...cron job or something else?

All this sounds relatively straightforward.  What do you think?

**Comment by mayanez** [comment]
Yeah that sounds totally doable.
I've started looking into doing something similar myself but for award tickets. I've already been able to figure out how to deal with the Qantas site and Alaska site. I'll pushing the code for that sometime soon. 

For the notifications, I'm looking into the various python libraries to send out the emails, if you have any suggestions let me know. 

The command-line stuff I've done before for another project so I'll look into reusing it here.

For the daily automation, I already have a script for that I just haven't pushed it to the project yet. It's using launchctl on OSX so if you have another OS you can still use it for guidance. 

I'm pretty busy this week, but I'm looking to have some time open next week for some tinkering. Let's update this issue as we progress.

**Comment by rockg** [comment]
I've been working on this and have a simple command line script that I would like to use to send out the email.  I have saved queries and an email will be sent with the results.  I'm using the same html template used in the web_app to display results, but this doesn't work unless the app is running.  However, when the application is started with app.run in the command-line script, it waits for input.  How can I render the html template with the search results either without having starting the web application or start it in such a manner that the rest of the script can execute?

**Comment by mayanez** [comment]
My guess is that the objects that the templates expects are not being set in your script. Look at the web_app.py file, specifically the render() method. If you pass the data in accordingly you should be able to use the same templates without having to start the actual web application. If you have any questions post your code and let me know.

**Comment by rockg** [comment]
Here's a snippet of code:

```
import sys
from flight_scraper.scraper import FlightScraper
from flask import Flask, render_template
from datetime import datetime
import mongoengine
import ConfigParser

app = Flask(__name__)

Config = ConfigParser.ConfigParser()
if Config.read('flight_scraper.cfg')==[]:
    print "Please copy flight_scraper.cfg.example to flight_scraper.cfg"
    raise Exception('Could not read config file')

try:
    host_string=Config.get("mongodb", "host")
    mongoengine.connect(Config.get("mongodb", "name"),host=host_string)
except ConfigParser.NoOptionError:
    mongoengine.connect(Config.get("mongodb", "name"))

app.config.update(
    DEBUG = True,
)

def _calendar_query(origin, dest, start_date, until_date, airlines,
                    day_range, max_stops):

    if not isinstance(start_date, datetime):
        start_date = datetime.strptime(start_date, '%m-%d-%Y')
        until_date = datetime.strptime(until_date, '%m-%d-%Y')

    flight_scraper  =   FlightScraper(origin, dest, start_date, until_date, 
                                      airlines=airlines, day_range=day_range, 
                                      max_stops=max_stops)
    return render_template('calendar_query.html', result=flight_scraper.search_calendar())


def main(argv=None):
    html = _calendar_query("BWI", "MSP", "7-1-2014", "7-7-2014",
                           "DL", [4, 5], 0)

    # Email the resulting html
if __name__=="__main__":
    sys.exit(main())
```

Which always gives AttributeError: 'NoneType' object has no attribute 'app' in render_template.

**Comment by rockg** [comment]
Figured it out, the key was to go through jinja2 directly.

```
    env = Environment(loader=PackageLoader(__name__, 'templates'))
    template    =   env.get_template('calendar_query.html')
    html        =   template.render(result=flight_scraper.search_calendar())
```

**Comment by mayanez** [comment]
Great!
